name: py

on: 
  push:
    branches: ["main"]

  workflow_dispatch:


jobs:
  scirpt:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is python script

      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #      python-version: 3.8 

      # - name: execute py script
      #   run: python run.py











# name: Release

# on:
#   - release

# jobs:
#   newrelic:
#     runs-on: ubuntu-latest
#     name: New Relic
#     steps:
#       - name: Set Release Version from Tag
#         run: echo "RELEASE_VERSION=${{ GITHUB_REF:10 }}" >> $GITHUB_ENV

#       - name: Create New Relic deployment marker
#         uses: newrelic/deployment-marker-action@v1
#         with:
#           apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
#           accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
#           applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
#           revision: "${{ env.RELEASE_VERSION }}"

      

